/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sjf7z6bo3vhi3k6qqjdrjh3e3m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-35nm4vmce5adve6mlc6ujf3tce",
    "aws_cognito_identity_pool_id": "us-east-1:9c6d1766-c6d4-4639-81e4-67d39527712b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eIxrhIBkA",
    "aws_user_pools_web_client_id": "885381605789-0os1knvalkduc05ula6sea0p2dak37hp.apps.googleusercontent.com",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "GENDER",
        "NAME",
        "NICKNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "instagramclone4e5e9260c1b9430db47f0a85cb84dfab222503-develop",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
